name: Setup Wasp Environment
description: Download Simba, SRL-T and WaspLib
author: Torwent
branding:
  icon: flag
  color: green

inputs:
  srlt:
    description: Wether to setup SRL-T or not. If wasplib is true this will be ignored.
    required: false
  wasplib:
    description: Wether to setup WaspLib or not. If this is true srlt will be ignored.
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Simba
      shell: bash
      run: |
        mkdir ./Simba
        curl --retry 5 -L -o ./Simba/Simba.exe https://github.com/Torwent/Simba/releases/download/Simba1400/Simba-Win32.exe
        chmod +x ./Simba/Simba.exe
        mkdir ./Simba/Includes/
        mkdir ./Simba/Scripts/

    - name: Setup SRL-T
      if: ${{ (inputs.wasplib == 'true') || (inputs.srlt == 'true') }}
      shell: bash
      run: |
        cd ./Simba/Includes/
        git clone https://github.com/Torwent/SRL-T.git

    - name: Setup WaspLib
      if: ${{ inputs.wasplib == 'true' }}
      shell: bash
      run: |
        cd ./Simba/Includes/
        git clone https://github.com/Torwent/WaspLib.git
