on: [push]
jobs:
  test:
    runs-on: windows-latest
    name: Test Simba Setup
    steps:
      - uses: actions/checkout@v4
      - name: Setup Simba
        uses: ./
        id: simba
        with:
          srl: true
          wasplib: true
      - name: Check result
        run: echo ${{ steps.simba.outputs.path }}
        shell: bash
